# .github/workflows/webhook_style_notify.yml

name: Webhook-style Discord notification

on:
  push:
    branches:
      - e72
jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord embed-style message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_E72 }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          AVATAR_URL: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "$(jq -nc \
              --arg username "GitHub" \
              --arg avatar_url "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" \
              --arg title "Push to ${BRANCH}" \
              --arg url "${COMMIT_URL}" \
              --arg description "${COMMIT_MSG}" \
              --arg author_name "${AUTHOR}" \
              --arg footer_text "${REPO}" \
              --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
              '{
                username: $username,
                avatar_url: $avatar_url,
                embeds: [{
                  title: $title,
                  url: $url,
                  description: $description,
                  color: 7506394,
                  author: { name: $author_name },
                  footer: { text: $footer_text },
                  timestamp: $timestamp
                }]
              }')" \
            "$DISCORD_WEBHOOK_E72"
