name: Notify Discord on push to main

on:
  push:
    branches:
      - e72
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send push info to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_E72 }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          echo "Sending Discord notification..."
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"content\": \"📦 **Push to \`${BRANCH}\` on \`${REPO}\`**\n🧑‍💻 **${AUTHOR}**: ${COMMIT_MSG}\n🔗 ${COMMIT_URL}\"
               }" \
               "$DISCORD_WEBHOOK"
